<?php

/**
 * CustomersApi
 * PHP version 8.1
 *
 * @category Class
 * @package  Monei
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
/**
 * MONEI API v1
 *
 * The MONEI API is organized around REST principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.
 *
 * The version of the OpenAPI document: 1.12.3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.14.0
 */
/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Monei\Api;

use Monei\Internal\GuzzleHttp\Client;
use Monei\Internal\GuzzleHttp\ClientInterface;
use Monei\Internal\GuzzleHttp\Exception\ConnectException;
use Monei\Internal\GuzzleHttp\Exception\RequestException;
use Monei\Internal\GuzzleHttp\Psr7\MultipartStream;
use Monei\Internal\GuzzleHttp\Psr7\Request;
use Monei\Internal\GuzzleHttp\RequestOptions;
use Monei\Internal\Psr\Http\Message\RequestInterface;
use Monei\Internal\Psr\Http\Message\ResponseInterface;
use Monei\ApiException;
use Monei\Configuration;
use Monei\FormDataProcessor;
use Monei\HeaderSelector;
use Monei\ObjectSerializer;

/**
 * CustomersApi Class Doc Comment
 *
 * @category Class
 * @package  Monei
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CustomersApi
{
    /**
     * @var ClientInterface
     */
    protected $client;
    /**
     * @var Configuration
     */
    protected $config;
    /**
     * @var HeaderSelector
     */
    protected $headerSelector;
    /**
     * @var int Host index
     */
    protected $hostIndex;
    /** @var string[] $contentTypes **/
    public const contentTypes = ['create' => ['application/json'], 'delete' => ['application/json'], 'deletePaymentMethod' => ['application/json'], 'get' => ['application/json'], 'listPaymentMethods' => ['application/json'], 'update' => ['application/json']];
    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(?ClientInterface $client = null, ?Configuration $config = null, ?HeaderSelector $selector = null, int $hostIndex = 0)
    {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }
    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }
    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }
    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }
    /**
     * Operation create
     *
     * Create Customer
     *
     * @param  \Monei\Model\CreateCustomerRequest $create_customer_request create_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function create($create_customer_request, string $contentType = self::contentTypes['create'][0])
    {
        list($response) = $this->createWithHttpInfo($create_customer_request, $contentType);
        return $response;
    }
    /**
     * Operation createWithHttpInfo
     *
     * Create Customer
     *
     * @param  \Monei\Model\CreateCustomerRequest $create_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function createWithHttpInfo($create_customer_request, string $contentType = self::contentTypes['create'][0])
    {
        $request = $this->createRequest($create_customer_request, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\Customer', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation createAsync
     *
     * Create Customer
     *
     * @param  \Monei\Model\CreateCustomerRequest $create_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAsync($create_customer_request, string $contentType = self::contentTypes['create'][0])
    {
        return $this->createAsyncWithHttpInfo($create_customer_request, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation createAsyncWithHttpInfo
     *
     * Create Customer
     *
     * @param  \Monei\Model\CreateCustomerRequest $create_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createAsyncWithHttpInfo($create_customer_request, string $contentType = self::contentTypes['create'][0])
    {
        $returnType = '\Monei\Model\Customer';
        $request = $this->createRequest($create_customer_request, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'create'
     *
     * @param  \Monei\Model\CreateCustomerRequest $create_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['create'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createRequest($create_customer_request, string $contentType = self::contentTypes['create'][0])
    {
        // verify the required parameter 'create_customer_request' is set
        if ($create_customer_request === null || is_array($create_customer_request) && count($create_customer_request) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $create_customer_request when calling create');
        }
        $resourcePath = '/customers';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($create_customer_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($create_customer_request));
            } else {
                $httpBody = $create_customer_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('POST', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation delete
     *
     * Delete Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\DeletedResource|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\ConflictError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function delete($id, string $contentType = self::contentTypes['delete'][0])
    {
        list($response) = $this->deleteWithHttpInfo($id, $contentType);
        return $response;
    }
    /**
     * Operation deleteWithHttpInfo
     *
     * Delete Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\DeletedResource|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\ConflictError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function deleteWithHttpInfo($id, string $contentType = self::contentTypes['delete'][0])
    {
        $request = $this->deleteRequest($id, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\DeletedResource', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 409:
                    return $this->handleResponseWithDataType('\Monei\Model\ConflictError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\DeletedResource', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\DeletedResource', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ConflictError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation deleteAsync
     *
     * Delete Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAsync($id, string $contentType = self::contentTypes['delete'][0])
    {
        return $this->deleteAsyncWithHttpInfo($id, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation deleteAsyncWithHttpInfo
     *
     * Delete Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deleteAsyncWithHttpInfo($id, string $contentType = self::contentTypes['delete'][0])
    {
        $returnType = '\Monei\Model\DeletedResource';
        $request = $this->deleteRequest($id, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'delete'
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['delete'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deleteRequest($id, string $contentType = self::contentTypes['delete'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || is_array($id) && count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling delete');
        }
        $resourcePath = '/customers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('DELETE', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation deletePaymentMethod
     *
     * Delete Payment Method
     *
     * @param  string $id The customer ID (required)
     * @param  string $token_id The payment method ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePaymentMethod'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\DeletedResource|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\ConflictError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function deletePaymentMethod($id, $token_id, string $contentType = self::contentTypes['deletePaymentMethod'][0])
    {
        list($response) = $this->deletePaymentMethodWithHttpInfo($id, $token_id, $contentType);
        return $response;
    }
    /**
     * Operation deletePaymentMethodWithHttpInfo
     *
     * Delete Payment Method
     *
     * @param  string $id The customer ID (required)
     * @param  string $token_id The payment method ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePaymentMethod'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\DeletedResource|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\ConflictError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function deletePaymentMethodWithHttpInfo($id, $token_id, string $contentType = self::contentTypes['deletePaymentMethod'][0])
    {
        $request = $this->deletePaymentMethodRequest($id, $token_id, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\DeletedResource', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 409:
                    return $this->handleResponseWithDataType('\Monei\Model\ConflictError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\DeletedResource', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\DeletedResource', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 409:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ConflictError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation deletePaymentMethodAsync
     *
     * Delete Payment Method
     *
     * @param  string $id The customer ID (required)
     * @param  string $token_id The payment method ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePaymentMethod'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePaymentMethodAsync($id, $token_id, string $contentType = self::contentTypes['deletePaymentMethod'][0])
    {
        return $this->deletePaymentMethodAsyncWithHttpInfo($id, $token_id, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation deletePaymentMethodAsyncWithHttpInfo
     *
     * Delete Payment Method
     *
     * @param  string $id The customer ID (required)
     * @param  string $token_id The payment method ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePaymentMethod'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function deletePaymentMethodAsyncWithHttpInfo($id, $token_id, string $contentType = self::contentTypes['deletePaymentMethod'][0])
    {
        $returnType = '\Monei\Model\DeletedResource';
        $request = $this->deletePaymentMethodRequest($id, $token_id, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'deletePaymentMethod'
     *
     * @param  string $id The customer ID (required)
     * @param  string $token_id The payment method ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['deletePaymentMethod'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function deletePaymentMethodRequest($id, $token_id, string $contentType = self::contentTypes['deletePaymentMethod'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || is_array($id) && count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling deletePaymentMethod');
        }
        // verify the required parameter 'token_id' is set
        if ($token_id === null || is_array($token_id) && count($token_id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $token_id when calling deletePaymentMethod');
        }
        $resourcePath = '/customers/{id}/payment-methods/{tokenId}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        // path params
        if ($token_id !== null) {
            $resourcePath = str_replace('{' . 'tokenId' . '}', ObjectSerializer::toPathValue($token_id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('DELETE', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation get
     *
     * Get Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function get($id, string $contentType = self::contentTypes['get'][0])
    {
        list($response) = $this->getWithHttpInfo($id, $contentType);
        return $response;
    }
    /**
     * Operation getWithHttpInfo
     *
     * Get Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function getWithHttpInfo($id, string $contentType = self::contentTypes['get'][0])
    {
        $request = $this->getRequest($id, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\Customer', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation getAsync
     *
     * Get Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAsync($id, string $contentType = self::contentTypes['get'][0])
    {
        return $this->getAsyncWithHttpInfo($id, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation getAsyncWithHttpInfo
     *
     * Get Customer
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getAsyncWithHttpInfo($id, string $contentType = self::contentTypes['get'][0])
    {
        $returnType = '\Monei\Model\Customer';
        $request = $this->getRequest($id, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'get'
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['get'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getRequest($id, string $contentType = self::contentTypes['get'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || is_array($id) && count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling get');
        }
        $resourcePath = '/customers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation listPaymentMethods
     *
     * List Payment Methods
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentMethods'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\CustomerPaymentMethod[]|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function listPaymentMethods($id, string $contentType = self::contentTypes['listPaymentMethods'][0])
    {
        list($response) = $this->listPaymentMethodsWithHttpInfo($id, $contentType);
        return $response;
    }
    /**
     * Operation listPaymentMethodsWithHttpInfo
     *
     * List Payment Methods
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentMethods'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\CustomerPaymentMethod[]|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function listPaymentMethodsWithHttpInfo($id, string $contentType = self::contentTypes['listPaymentMethods'][0])
    {
        $request = $this->listPaymentMethodsRequest($id, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\CustomerPaymentMethod[]', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\CustomerPaymentMethod[]', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\CustomerPaymentMethod[]', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation listPaymentMethodsAsync
     *
     * List Payment Methods
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentMethods'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentMethodsAsync($id, string $contentType = self::contentTypes['listPaymentMethods'][0])
    {
        return $this->listPaymentMethodsAsyncWithHttpInfo($id, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation listPaymentMethodsAsyncWithHttpInfo
     *
     * List Payment Methods
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentMethods'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function listPaymentMethodsAsyncWithHttpInfo($id, string $contentType = self::contentTypes['listPaymentMethods'][0])
    {
        $returnType = '\Monei\Model\CustomerPaymentMethod[]';
        $request = $this->listPaymentMethodsRequest($id, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'listPaymentMethods'
     *
     * @param  string $id The customer ID (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['listPaymentMethods'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function listPaymentMethodsRequest($id, string $contentType = self::contentTypes['listPaymentMethods'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || is_array($id) && count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling listPaymentMethods');
        }
        $resourcePath = '/customers/{id}/payment-methods';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('GET', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Operation update
     *
     * Update Customer
     *
     * @param  string $id The customer ID (required)
     * @param  \Monei\Model\UpdateCustomerRequest $update_customer_request update_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError
     */
    public function update($id, $update_customer_request, string $contentType = self::contentTypes['update'][0])
    {
        list($response) = $this->updateWithHttpInfo($id, $update_customer_request, $contentType);
        return $response;
    }
    /**
     * Operation updateWithHttpInfo
     *
     * Update Customer
     *
     * @param  string $id The customer ID (required)
     * @param  \Monei\Model\UpdateCustomerRequest $update_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \Monei\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \Monei\Model\Customer|\Monei\Model\BadRequestError|\Monei\Model\UnauthorizedError|\Monei\Model\NotFoundError|\Monei\Model\UnprocessableEntityError|\Monei\Model\InternalServerError|\Monei\Model\ServiceUnavailableError, HTTP status code, HTTP response headers (array of strings)
     */
    public function updateWithHttpInfo($id, $update_customer_request, string $contentType = self::contentTypes['update'][0])
    {
        $request = $this->updateRequest($id, $update_customer_request, $contentType);
        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), $e->getResponse() ? $e->getResponse()->getHeaders() : null, $e->getResponse() ? (string) $e->getResponse()->getBody() : null);
            } catch (ConnectException $e) {
                throw new ApiException("[{$e->getCode()}] {$e->getMessage()}", (int) $e->getCode(), null, null);
            }
            $statusCode = $response->getStatusCode();
            switch ($statusCode) {
                case 200:
                    return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
                case 400:
                    return $this->handleResponseWithDataType('\Monei\Model\BadRequestError', $request, $response);
                case 401:
                    return $this->handleResponseWithDataType('\Monei\Model\UnauthorizedError', $request, $response);
                case 404:
                    return $this->handleResponseWithDataType('\Monei\Model\NotFoundError', $request, $response);
                case 422:
                    return $this->handleResponseWithDataType('\Monei\Model\UnprocessableEntityError', $request, $response);
                case 500:
                    return $this->handleResponseWithDataType('\Monei\Model\InternalServerError', $request, $response);
                case 503:
                    return $this->handleResponseWithDataType('\Monei\Model\ServiceUnavailableError', $request, $response);
            }
            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, (string) $request->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
            }
            return $this->handleResponseWithDataType('\Monei\Model\Customer', $request, $response);
        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\Customer', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 400:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\BadRequestError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 401:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnauthorizedError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 404:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\NotFoundError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 422:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\UnprocessableEntityError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 500:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\InternalServerError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
                case 503:
                    $data = ObjectSerializer::deserialize($e->getResponseBody(), '\Monei\Model\ServiceUnavailableError', $e->getResponseHeaders());
                    $e->setResponseObject($data);
                    throw $e;
            }
            throw $e;
        }
    }
    /**
     * Operation updateAsync
     *
     * Update Customer
     *
     * @param  string $id The customer ID (required)
     * @param  \Monei\Model\UpdateCustomerRequest $update_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsync($id, $update_customer_request, string $contentType = self::contentTypes['update'][0])
    {
        return $this->updateAsyncWithHttpInfo($id, $update_customer_request, $contentType)->then(function ($response) {
            return $response[0];
        });
    }
    /**
     * Operation updateAsyncWithHttpInfo
     *
     * Update Customer
     *
     * @param  string $id The customer ID (required)
     * @param  \Monei\Model\UpdateCustomerRequest $update_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function updateAsyncWithHttpInfo($id, $update_customer_request, string $contentType = self::contentTypes['update'][0])
    {
        $returnType = '\Monei\Model\Customer';
        $request = $this->updateRequest($id, $update_customer_request, $contentType);
        return $this->client->sendAsync($request, $this->createHttpClientOption())->then(function ($response) use ($returnType) {
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody();
                //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }
            return [ObjectSerializer::deserialize($content, $returnType, []), $response->getStatusCode(), $response->getHeaders()];
        }, function ($exception) {
            $response = $exception->getResponse();
            $statusCode = $response->getStatusCode();
            throw new ApiException(sprintf('[%d] Error connecting to the API (%s)', $statusCode, $exception->getRequest()->getUri()), $statusCode, $response->getHeaders(), (string) $response->getBody());
        });
    }
    /**
     * Create request for operation 'update'
     *
     * @param  string $id The customer ID (required)
     * @param  \Monei\Model\UpdateCustomerRequest $update_customer_request (required)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['update'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function updateRequest($id, $update_customer_request, string $contentType = self::contentTypes['update'][0])
    {
        // verify the required parameter 'id' is set
        if ($id === null || is_array($id) && count($id) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $id when calling update');
        }
        // verify the required parameter 'update_customer_request' is set
        if ($update_customer_request === null || is_array($update_customer_request) && count($update_customer_request) === 0) {
            throw new \InvalidArgumentException('Missing the required parameter $update_customer_request when calling update');
        }
        $resourcePath = '/customers/{id}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = \false;
        // path params
        if ($id !== null) {
            $resourcePath = str_replace('{' . 'id' . '}', ObjectSerializer::toPathValue($id), $resourcePath);
        }
        $headers = $this->headerSelector->selectHeaders(['application/json'], $contentType, $multipart);
        // for model (json/xml)
        if (isset($update_customer_request)) {
            if (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the body
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($update_customer_request));
            } else {
                $httpBody = $update_customer_request;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = ['name' => $formParamName, 'contents' => $formParamValueItem];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);
            } elseif (stripos($headers['Content-Type'], 'application/json') !== \false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \Monei\Internal\GuzzleHttp\json_encode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Authorization');
        if ($apiKey !== null) {
            $headers['Authorization'] = $apiKey;
        }
        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }
        $headers = array_merge($defaultHeaders, $headerParams, $headers);
        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request('PUT', $operationHost . $resourcePath . ($query ? "?{$query}" : ''), $headers, $httpBody);
    }
    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }
        return $options;
    }
    private function handleResponseWithDataType(string $dataType, RequestInterface $request, ResponseInterface $response): array
    {
        if ($dataType === '\SplFileObject') {
            $content = $response->getBody();
            //stream goes to serializer
        } else {
            $content = (string) $response->getBody();
            if ($dataType !== 'string') {
                try {
                    $content = json_decode($content, \false, 512, \JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw new ApiException(sprintf('Error JSON decoding server response (%s)', $request->getUri()), $response->getStatusCode(), $response->getHeaders(), $content);
                }
            }
        }
        return [ObjectSerializer::deserialize($content, $dataType, []), $response->getStatusCode(), $response->getHeaders()];
    }
    private function responseWithinRangeCode(string $rangeCode, int $statusCode): bool
    {
        $left = (int) ($rangeCode[0] . '00');
        $right = (int) ($rangeCode[0] . '99');
        return $statusCode >= $left && $statusCode <= $right;
    }
}
