<?php

/**
 * PaymentBillingDetailsTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  Monei
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * MONEI API v1
 *
 * The MONEI API is organized around [REST](https://en.wikipedia.org/wiki/Representational_State_Transfer) principles. Our API is designed to be intuitive and developer-friendly.  ### Base URL  All API requests should be made to:  ``` https://api.monei.com/v1 ```  ### Environment  MONEI provides two environments:  - **Test Environment**: For development and testing without processing real payments - **Live Environment**: For processing real transactions in production  ### Client Libraries  We provide official SDKs to simplify integration:  - [PHP SDK](https://github.com/MONEI/monei-php-sdk) - [Python SDK](https://github.com/MONEI/monei-python-sdk) - [Node.js SDK](https://github.com/MONEI/monei-node-sdk) - [Postman Collection](https://postman.monei.com/)  Our SDKs handle authentication, error handling, and request formatting automatically.  You can download the OpenAPI specification from the https://js.monei.com/api/v1/openapi.json and generate your own client library using the [OpenAPI Generator](https://openapi-generator.tech/).  ### Important Requirements  - All API requests must be made over HTTPS - If you are not using our official SDKs, you **must provide a valid `User-Agent` header** with each request - Requests without proper authentication will return a `401 Unauthorized` error  ### Error Handling  The API returns consistent error codes and messages to help you troubleshoot issues. Each response includes a `statusCode` attribute indicating the outcome of your request.  ### Rate Limits  The API implements rate limiting to ensure stability. If you exceed the limits, requests will return a `429 Too Many Requests` status code.  # Authentication  <!-- Redoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 1.5.8
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace Monei\Test\Model;

use PHPUnit\Framework\TestCase;
use Monei\Model\PaymentBillingDetails;
use Monei\Model\Address;

/**
 * PaymentBillingDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Billing information associated with the payment method at the time of the transaction.
 * @package     Monei
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class PaymentBillingDetailsTest extends TestCase
{
    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "PaymentBillingDetails"
     */
    public function testPaymentBillingDetails()
    {
        $billingDetails = new PaymentBillingDetails();
        $this->assertInstanceOf(PaymentBillingDetails::class, $billingDetails);

        // Test with constructor parameters
        $address = new Address([
            'country' => 'ES',
            'city' => 'Barcelona',
            'line1' => 'Calle Principal 123',
            'zip' => '08001',
            'state' => 'Catalonia'
        ]);

        $data = [
            'name' => 'John Doe',
            'email' => 'john@example.com',
            'phone' => '+34612345678',
            'company' => 'Acme Inc',
            'tax_id' => 'ES12345678Z',
            'address' => $address
        ];

        $billingDetails = new PaymentBillingDetails($data);
        $this->assertEquals($data['name'], $billingDetails->getName());
        $this->assertEquals($data['email'], $billingDetails->getEmail());
        $this->assertEquals($data['phone'], $billingDetails->getPhone());
        $this->assertEquals($data['company'], $billingDetails->getCompany());
        $this->assertEquals($data['tax_id'], $billingDetails->getTaxId());
        $this->assertSame($address, $billingDetails->getAddress());
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
        $billingDetails = new PaymentBillingDetails();
        $expected = 'Jane Smith';
        $billingDetails->setName($expected);
        $this->assertEquals($expected, $billingDetails->getName());
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
        $billingDetails = new PaymentBillingDetails();
        $expected = 'jane@example.com';
        $billingDetails->setEmail($expected);
        $this->assertEquals($expected, $billingDetails->getEmail());
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
        $billingDetails = new PaymentBillingDetails();
        $expected = '+34698765432';
        $billingDetails->setPhone($expected);
        $this->assertEquals($expected, $billingDetails->getPhone());
    }

    /**
     * Test attribute "company"
     */
    public function testPropertyCompany()
    {
        $billingDetails = new PaymentBillingDetails();
        $expected = 'Globex Corporation';
        $billingDetails->setCompany($expected);
        $this->assertEquals($expected, $billingDetails->getCompany());
    }

    /**
     * Test attribute "tax_id"
     */
    public function testPropertyTaxId()
    {
        $billingDetails = new PaymentBillingDetails();
        $expected = 'ES87654321X';
        $billingDetails->setTaxId($expected);
        $this->assertEquals($expected, $billingDetails->getTaxId());
    }

    /**
     * Test attribute "address"
     */
    public function testPropertyAddress()
    {
        $billingDetails = new PaymentBillingDetails();

        // Test with null value
        $this->assertNull($billingDetails->getAddress());

        // Test with Address object
        $address = new Address();
        $address->setCountry('IT');
        $address->setCity('Rome');
        $address->setLine1('Via Roma 42');
        $address->setZip('00100');

        $billingDetails->setAddress($address);
        $retrievedAddress = $billingDetails->getAddress();

        $this->assertInstanceOf(Address::class, $retrievedAddress);
        $this->assertEquals('IT', $retrievedAddress->getCountry());
        $this->assertEquals('Rome', $retrievedAddress->getCity());
        $this->assertEquals('Via Roma 42', $retrievedAddress->getLine1());
        $this->assertEquals('00100', $retrievedAddress->getZip());
    }
}
